create table "public"."money_out" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "amount" real not null,
    "tags" text[] not null,
    "period" interval
);


alter table "public"."money_out" enable row level security;

CREATE UNIQUE INDEX money_out_pkey ON public.money_out USING btree (id);

alter table "public"."money_out" add constraint "money_out_pkey" PRIMARY KEY using index "money_out_pkey";


